---
apiVersion: v1
data:
{{- range $k, $v := .Values.local_nodes }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
  slack-alert-token: {{ b64enc .Values.slack_alert_token }}
kind: Secret
metadata:
  name: polkadot-node-keys
  namespace: {{ .Release.Namespace }}
