{{- if .Values.session_key_check.enabled }}
---
apiVersion: v1
data:
  slack-alert-token: {{ b64enc .Values.session_key_check.slack_alert_token }}
kind: Secret
metadata:
  name: polkadot-val-secrets
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: v1
data:
{{- range $k, $v := .Values.local_nodes }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
kind: Secret
metadata:
  name: polkadot-node-keys
  namespace: {{ .Release.Namespace }}

